# Generated by Django 4.1.7 on 2023-03-19 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50)),
                ('content', models.TextField(help_text='Описание')),
                ('is_complete', models.BooleanField(default=False, help_text='Выполнен')),
                ('timestamp_create', models.DateTimeField(auto_now_add=True, help_text='Когда создан', null=True)),
                ('timestamp_done', models.DateTimeField(blank=True, editable=False, help_text='Когда выполнен', null=True)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50)),
                ('date_start', models.DateField(help_text='Дата начала')),
                ('date_end', models.DateField(help_text='Дата окончания')),
                ('project', models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.PROTECT, related_name='sprints', to='tmapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Статус задачи', max_length=50)),
                ('parent_status', models.ForeignKey(blank=True, help_text='Родительский статус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substatus', to='tmapp.status')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50)),
                ('content', models.TextField(help_text='Описание')),
                ('is_complete', models.BooleanField(default=False, help_text='Выполнена')),
                ('timestamp_create', models.DateTimeField(auto_now_add=True, help_text='Когда создана', null=True)),
                ('timestamp_done', models.DateTimeField(blank=True, editable=False, help_text='Когда выполнена', null=True)),
                ('executor', models.ForeignKey(blank=True, help_text='Исполнитель', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tmapp.project')),
                ('sprint', models.ForeignKey(blank=True, help_text='Спринт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tmapp.sprint')),
                ('status', models.ForeignKey(blank=True, help_text='Статус', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tmapp.status')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50)),
                ('content', models.TextField(help_text='Описание')),
                ('is_complete', models.BooleanField(default=False, help_text='Выполнена')),
                ('timestamp_create', models.DateTimeField(blank=True, editable=False, help_text='Когда создана', null=True)),
                ('timestamp_done', models.DateTimeField(blank=True, editable=False, help_text='Когда выполнена', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('executor', models.ForeignKey(blank=True, db_constraint=False, help_text='Исполнитель', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, help_text='Проект', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.project')),
                ('sprint', models.ForeignKey(blank=True, db_constraint=False, help_text='Спринт', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.sprint')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, help_text='Статус', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.status')),
            ],
            options={
                'verbose_name': 'historical задача',
                'verbose_name_plural': 'historical задачи',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
